# Generated by Django 5.1 on 2025-03-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beds',
            name='Bed_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='beds',
            name='Bed_type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='beds',
            name='Hospital_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='beds',
            name='Room_number',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='beds',
            name='Ward_number',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feed',
            name='message',
            field=models.TextField(),
        ),
    ]
