# Generated by Django 5.1 on 2025-03-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_beds_bed_id_alter_beds_bed_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorregistration',
            name='Licence_issuing_authority',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='doctorregistration',
            name='Medical_license_number',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='doctorregistration',
            name='Qualification',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='doctorregistration',
            name='Specialization',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='doctorregistration',
            name='Year_of_experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctorregistration',
            name='contact_number',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='patient_info',
            name='Bed_type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patient_info',
            name='Disease',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patient_info',
            name='Room_number',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patient_info',
            name='Ward_number',
            field=models.TextField(),
        ),
    ]
