# Generated by Django 5.1 on 2025-03-10 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_doctorregistration_licence_issuing_authority_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booked_slot',
            new_name='BookedSlot',
        ),
    ]
