# Generated by Django 5.1 on 2025-03-10 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_booked_slot_bookedslot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookedSlot',
            new_name='Booked_slot',
        ),
    ]
