# Generated by Django 5.1 on 2025-03-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_hospitalregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HospitalRegistration',
        ),
        migrations.AddField(
            model_name='hospitalinfo',
            name='city',
            field=models.CharField(blank=True, default='Unknown City', max_length=50),
        ),
        migrations.AddField(
            model_name='hospitalinfo',
            name='email',
            field=models.CharField(default='example@example.com', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='hospitalinfo',
            name='hospital_type',
            field=models.CharField(choices=[('Government', 'Government'), ('Private', 'Private'), ('Charitable', 'Charitable')], default='Private', max_length=50),
        ),
        migrations.AddField(
            model_name='hospitalinfo',
            name='phone_number',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospitalinfo',
            name='registration_number',
            field=models.TextField(default='Not Registered'),
        ),
        migrations.AddField(
            model_name='hospitalinfo',
            name='specialties',
            field=models.TextField(default='General'),
        ),
        migrations.AddField(
            model_name='hospitalinfo',
            name='state',
            field=models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Chandigarh', 'Chandigarh'), (' Dadra and Nagar Haveli and Daman and Diu', ' Dadra and Nagar Haveli and Daman and Diu'), ('Lakshadweep', 'Lakshadweep'), ('Delhi', 'Delhi'), ('Puducherry', 'Puducherry')], default='State1', max_length=50),
        ),
        migrations.AddField(
            model_name='hospitalinfo',
            name='website_url',
            field=models.TextField(default='http://example.com'),
        ),
        migrations.AddField(
            model_name='hospitalinfo',
            name='zip_code',
            field=models.TextField(default='000000'),
        ),
    ]
