# Generated by Django 5.1 on 2025-03-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_delete_hospitalregistration_hospitalinfo_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalinfo',
            name='password',
            field=models.TextField(default='1234'),
        ),
    ]
