# Generated by Django 5.1 on 2025-03-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_hospitalinfo_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalinfo',
            name='hospital_image',
            field=models.ImageField(default='', upload_to='hospital_images'),
        ),
    ]
