# Generated by Django 5.1 on 2025-03-11 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_hospitalinfo_hospital_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beds',
            name='Hospital_id',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='beds',
            name='Hospital_name',
            field=models.TextField(default=''),
        ),
    ]
