# Generated by Django 5.1 on 2025-03-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_beds_hospital_id_alter_beds_hospital_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked_slot',
            name='appointment_id',
            field=models.TextField(default=''),
        ),
    ]
