# Generated by Django 5.1 on 2025-03-31 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_booked_slot_appointment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalinformation',
            name='patient_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=300),
        ),
        migrations.AlterField(
            model_name='patient_info',
            name='patient_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=300),
        ),
    ]
